// Code generated by strsql; DO NOT EDIT.
package models

import (
	"reflect"

	"github.com/kcmvp/strsql"
)

// Helper function to safely get reflect.Type
func typeOf[T any]() reflect.Type {
	return reflect.TypeOf(*new(T))
}

// Helper function to safely get a field type by name.
func fieldType(typ reflect.Type, name string) reflect.Type {
	field, ok := typ.FieldByName(name)
	if !ok {
		panic("strsql_gen: " + typ.String() + "." + name + " not found")
	}
	return field.Type
}

var _ProductType = typeOf[Product]()

// ProductSch is the schema mapping for the Product entity.
var ProductSch = struct {
	ID    strsql.Attribute[Product]
	Name  strsql.Attribute[Product]
	Price strsql.Attribute[Product]
	Stock strsql.Attribute[Product]
}{
	ID:    strsql.Of[Product]("ID", "id", fieldType(_ProductType, "ID")),
	Name:  strsql.Of[Product]("Name", "name", fieldType(_ProductType, "Name")),
	Price: strsql.Of[Product]("Price", "price", fieldType(_ProductType, "Price")),
	Stock: strsql.Of[Product]("Stock", "stock", fieldType(_ProductType, "Stock")),
}
var _OrderType = typeOf[Order]()

// OrderSch is the schema mapping for the Order entity.
var OrderSch = struct {
	ID         strsql.Attribute[Order]
	CustomerID strsql.Attribute[Order]
	Status     strsql.Attribute[Order]
	IsPaid     strsql.Attribute[Order]
	CreatedAt  strsql.Attribute[Order]
}{
	ID:         strsql.Of[Order]("ID", "id", fieldType(_OrderType, "ID")),
	CustomerID: strsql.Of[Order]("CustomerID", "customer_id", fieldType(_OrderType, "CustomerID")),
	Status:     strsql.Of[Order]("Status", "status", fieldType(_OrderType, "Status")),
	IsPaid:     strsql.Of[Order]("IsPaid", "is_paid", fieldType(_OrderType, "IsPaid")),
	CreatedAt:  strsql.Of[Order]("CreatedAt", "created_at", fieldType(_OrderType, "CreatedAt")),
}
var _OrderItemType = typeOf[OrderItem]()

// OrderItemSch is the schema mapping for the OrderItem entity.
var OrderItemSch = struct {
	ID        strsql.Attribute[OrderItem]
	OrderID   strsql.Attribute[OrderItem]
	ProductID strsql.Attribute[OrderItem]
	Quantity  strsql.Attribute[OrderItem]
	UnitPrice strsql.Attribute[OrderItem]
}{
	ID:        strsql.Of[OrderItem]("ID", "id", fieldType(_OrderItemType, "ID")),
	OrderID:   strsql.Of[OrderItem]("OrderID", "order_id", fieldType(_OrderItemType, "OrderID")),
	ProductID: strsql.Of[OrderItem]("ProductID", "product_id", fieldType(_OrderItemType, "ProductID")),
	Quantity:  strsql.Of[OrderItem]("Quantity", "quantity", fieldType(_OrderItemType, "Quantity")),
	UnitPrice: strsql.Of[OrderItem]("UnitPrice", "unit_price", fieldType(_OrderItemType, "UnitPrice")),
}
