// Code generated by strsql; DO NOT EDIT.
package models

import (
	"reflect"

	"github.com/kcmvp/strsql"
)

// Helper function to safely get reflect.Type
func typeOf[T any]() reflect.Type {
	return reflect.TypeOf(*new(T))
}

// ProductSch is the schema mapping for the Product entity.
var ProductSch = struct {
	ID    strsql.Attribute[Product]
	Name  strsql.Attribute[Product]
	Price strsql.Attribute[Product]
	Stock strsql.Attribute[Product]
}{
	ID: strsql.Of[Product]("ID", "id", func() reflect.Type {
		field, ok := reflect.TypeOf(*new(Product)).FieldByName("ID")
		if !ok {
			panic("strsql_gen: Product.ID not found")
		}
		return field.Type
	}()),
	Name: strsql.Of[Product]("Name", "name", func() reflect.Type {
		field, ok := reflect.TypeOf(*new(Product)).FieldByName("Name")
		if !ok {
			panic("strsql_gen: Product.Name not found")
		}
		return field.Type
	}()),
	Price: strsql.Of[Product]("Price", "price", func() reflect.Type {
		field, ok := reflect.TypeOf(*new(Product)).FieldByName("Price")
		if !ok {
			panic("strsql_gen: Product.Price not found")
		}
		return field.Type
	}()),
	Stock: strsql.Of[Product]("Stock", "stock", func() reflect.Type {
		field, ok := reflect.TypeOf(*new(Product)).FieldByName("Stock")
		if !ok {
			panic("strsql_gen: Product.Stock not found")
		}
		return field.Type
	}()),
}

// OrderSch is the schema mapping for the Order entity.
var OrderSch = struct {
	ID         strsql.Attribute[Order]
	CustomerID strsql.Attribute[Order]
	Status     strsql.Attribute[Order]
	IsPaid     strsql.Attribute[Order]
	CreatedAt  strsql.Attribute[Order]
}{
	ID: strsql.Of[Order]("ID", "id", func() reflect.Type {
		field, ok := reflect.TypeOf(*new(Order)).FieldByName("ID")
		if !ok {
			panic("strsql_gen: Order.ID not found")
		}
		return field.Type
	}()),
	CustomerID: strsql.Of[Order]("CustomerID", "customer_id", func() reflect.Type {
		field, ok := reflect.TypeOf(*new(Order)).FieldByName("CustomerID")
		if !ok {
			panic("strsql_gen: Order.CustomerID not found")
		}
		return field.Type
	}()),
	Status: strsql.Of[Order]("Status", "status", func() reflect.Type {
		field, ok := reflect.TypeOf(*new(Order)).FieldByName("Status")
		if !ok {
			panic("strsql_gen: Order.Status not found")
		}
		return field.Type
	}()),
	IsPaid: strsql.Of[Order]("IsPaid", "is_paid", func() reflect.Type {
		field, ok := reflect.TypeOf(*new(Order)).FieldByName("IsPaid")
		if !ok {
			panic("strsql_gen: Order.IsPaid not found")
		}
		return field.Type
	}()),
	CreatedAt: strsql.Of[Order]("CreatedAt", "created_at", func() reflect.Type {
		field, ok := reflect.TypeOf(*new(Order)).FieldByName("CreatedAt")
		if !ok {
			panic("strsql_gen: Order.CreatedAt not found")
		}
		return field.Type
	}()),
}

// OrderItemSch is the schema mapping for the OrderItem entity.
var OrderItemSch = struct {
	ID        strsql.Attribute[OrderItem]
	OrderID   strsql.Attribute[OrderItem]
	ProductID strsql.Attribute[OrderItem]
	Quantity  strsql.Attribute[OrderItem]
	UnitPrice strsql.Attribute[OrderItem]
}{
	ID: strsql.Of[OrderItem]("ID", "id", func() reflect.Type {
		field, ok := reflect.TypeOf(*new(OrderItem)).FieldByName("ID")
		if !ok {
			panic("strsql_gen: OrderItem.ID not found")
		}
		return field.Type
	}()),
	OrderID: strsql.Of[OrderItem]("OrderID", "order_id", func() reflect.Type {
		field, ok := reflect.TypeOf(*new(OrderItem)).FieldByName("OrderID")
		if !ok {
			panic("strsql_gen: OrderItem.OrderID not found")
		}
		return field.Type
	}()),
	ProductID: strsql.Of[OrderItem]("ProductID", "product_id", func() reflect.Type {
		field, ok := reflect.TypeOf(*new(OrderItem)).FieldByName("ProductID")
		if !ok {
			panic("strsql_gen: OrderItem.ProductID not found")
		}
		return field.Type
	}()),
	Quantity: strsql.Of[OrderItem]("Quantity", "quantity", func() reflect.Type {
		field, ok := reflect.TypeOf(*new(OrderItem)).FieldByName("Quantity")
		if !ok {
			panic("strsql_gen: OrderItem.Quantity not found")
		}
		return field.Type
	}()),
	UnitPrice: strsql.Of[OrderItem]("UnitPrice", "unit_price", func() reflect.Type {
		field, ok := reflect.TypeOf(*new(OrderItem)).FieldByName("UnitPrice")
		if !ok {
			panic("strsql_gen: OrderItem.UnitPrice not found")
		}
		return field.Type
	}()),
}
