// Code generated by strsql; DO NOT EDIT.
package models

import (
	"reflect"

	"github.com/kcmvp/strsql"
)

// Helper function to safely get reflect.Type
func typeOf[T any]() reflect.Type {
	return reflect.TypeOf(*new(T))
}

// ProductSch is the schema mapping for the Product entity.
var ProductSch = struct {
	ID    strsql.Attribute[Product]
	Name  strsql.Attribute[Product]
	Price strsql.Attribute[Product]
	Stock strsql.Attribute[Product]
}{
	ID:    strsql.Of[Product]("ID", "id", reflect.TypeOf(*new(Product)).Field(0).Type),
	Name:  strsql.Of[Product]("Name", "name", reflect.TypeOf(*new(Product)).Field(1).Type),
	Price: strsql.Of[Product]("Price", "price", reflect.TypeOf(*new(Product)).Field(2).Type),
	Stock: strsql.Of[Product]("Stock", "stock", reflect.TypeOf(*new(Product)).Field(3).Type),
}

// OrderSch is the schema mapping for the Order entity.
var OrderSch = struct {
	ID         strsql.Attribute[Order]
	CustomerID strsql.Attribute[Order]
	Status     strsql.Attribute[Order]
	IsPaid     strsql.Attribute[Order]
	CreatedAt  strsql.Attribute[Order]
}{
	ID:         strsql.Of[Order]("ID", "id", reflect.TypeOf(*new(Order)).Field(0).Type),
	CustomerID: strsql.Of[Order]("CustomerID", "customer_id", reflect.TypeOf(*new(Order)).Field(1).Type),
	Status:     strsql.Of[Order]("Status", "status", reflect.TypeOf(*new(Order)).Field(2).Type),
	IsPaid:     strsql.Of[Order]("IsPaid", "is_paid", reflect.TypeOf(*new(Order)).Field(3).Type),
	CreatedAt:  strsql.Of[Order]("CreatedAt", "created_at", reflect.TypeOf(*new(Order)).Field(4).Type),
}

// OrderItemSch is the schema mapping for the OrderItem entity.
var OrderItemSch = struct {
	ID        strsql.Attribute[OrderItem]
	OrderID   strsql.Attribute[OrderItem]
	ProductID strsql.Attribute[OrderItem]
	Quantity  strsql.Attribute[OrderItem]
	UnitPrice strsql.Attribute[OrderItem]
}{
	ID:        strsql.Of[OrderItem]("ID", "id", reflect.TypeOf(*new(OrderItem)).Field(0).Type),
	OrderID:   strsql.Of[OrderItem]("OrderID", "order_id", reflect.TypeOf(*new(OrderItem)).Field(1).Type),
	ProductID: strsql.Of[OrderItem]("ProductID", "product_id", reflect.TypeOf(*new(OrderItem)).Field(2).Type),
	Quantity:  strsql.Of[OrderItem]("Quantity", "quantity", reflect.TypeOf(*new(OrderItem)).Field(3).Type),
	UnitPrice: strsql.Of[OrderItem]("UnitPrice", "unit_price", reflect.TypeOf(*new(OrderItem)).Field(4).Type),
}
